"""
Provider abstraction layer.

This module provides a unified interface for interacting with different LLM providers.
"""

from .anthropic import ANTHROPIC_AVAILABLE, AnthropicProvider
from .base import BaseProvider, Provider
from .google import GOOGLE_AVAILABLE, GoogleProvider
from .openai import OpenAIProvider
from .types import (
    AudioSpeechResult,
    AudioTranscriptionResult,
    BackgroundResponseResult,
    DeepResearchRunResult,
    CompactionResult,
    CompletionResult,
    ConversationItemResource,
    ConversationItemsPage,
    ConversationResource,
    DeletionResult,
    EmbeddingResult,
    FileContentResult,
    FileResource,
    FilesPage,
    FineTuningJobEventsPage,
    FineTuningJobResult,
    FineTuningJobsPage,
    GeneratedImage,
    ImageGenerationResult,
    Message,
    MessageInput,
    ModerationResult,
    NormalizedOutputItem,
    Role,
    StreamEvent,
    StreamEventType,
    ToolCall,
    ToolCallDelta,
    UploadPartResource,
    UploadResource,
    Usage,
    RealtimeCallResult,
    RealtimeConnection,
    RealtimeClientSecretResult,
    RealtimeEventResult,
    RealtimeResponseOutput,
    RealtimeTranscriptionSessionResult,
    VectorStoreFileContentResult,
    VectorStoreFileBatchResource,
    VectorStoreFileResource,
    VectorStoreFilesPage,
    VectorStoreResource,
    VectorStoreSearchResult,
    VectorStoresPage,
    WebhookEventResult,
    normalize_messages,
)

__all__ = [
    # Protocols and base classes
    "Provider",
    "BaseProvider",
    # Provider implementations
    "OpenAIProvider",
    "AnthropicProvider",
    "ANTHROPIC_AVAILABLE",
    "GoogleProvider",
    "GOOGLE_AVAILABLE",
    # Types
    "Role",
    "StreamEventType",
    "ToolCall",
    "ToolCallDelta",
    "UploadResource",
    "UploadPartResource",
    "Message",
    "Usage",
    "StreamEvent",
    "CompletionResult",
    "BackgroundResponseResult",
    "DeepResearchRunResult",
    "ConversationResource",
    "CompactionResult",
    "DeletionResult",
    "FileResource",
    "FilesPage",
    "FileContentResult",
    "ConversationItemResource",
    "ConversationItemsPage",
    "ModerationResult",
    "GeneratedImage",
    "ImageGenerationResult",
    "AudioTranscriptionResult",
    "AudioSpeechResult",
    "VectorStoreResource",
    "VectorStoresPage",
    "VectorStoreSearchResult",
    "FineTuningJobResult",
    "FineTuningJobsPage",
    "FineTuningJobEventsPage",
    "RealtimeClientSecretResult",
    "RealtimeCallResult",
    "RealtimeTranscriptionSessionResult",
    "RealtimeEventResult",
    "RealtimeResponseOutput",
    "RealtimeConnection",
    "WebhookEventResult",
    "VectorStoreFileResource",
    "VectorStoreFilesPage",
    "VectorStoreFileContentResult",
    "VectorStoreFileBatchResource",
    "EmbeddingResult",
    "NormalizedOutputItem",
    "MessageInput",
    "normalize_messages",
]
