"""
Stable shared type namespace for llm-client.

Use this module when you want a single import path for the package's common
request, response, streaming, and cancellation datatypes.
"""

from .cancellation import CancellationToken, CancelledError
from .providers.types import (
    AudioSpeechResult,
    AudioTranscriptionResult,
    BackgroundResponseResult,
    DeepResearchRunResult,
    CompactionResult,
    CompletionResult,
    ConversationItemResource,
    ConversationItemsPage,
    ConversationResource,
    DeletionResult,
    EmbeddingResult,
    FileContentResult,
    FileResource,
    FilesPage,
    FineTuningJobEventsPage,
    FineTuningJobResult,
    FineTuningJobsPage,
    GeneratedImage,
    ImageGenerationResult,
    Message,
    MessageInput,
    ModerationResult,
    NormalizedOutputItem,
    Role,
    StreamEvent,
    StreamEventType,
    ToolCall,
    ToolCallDelta,
    UploadPartResource,
    UploadResource,
    Usage,
    RealtimeCallResult,
    RealtimeConnection,
    RealtimeClientSecretResult,
    RealtimeEventResult,
    RealtimeTranscriptionSessionResult,
    VectorStoreFileContentResult,
    VectorStoreFileBatchResource,
    VectorStoreFileResource,
    VectorStoreFilesPage,
    VectorStoreResource,
    VectorStoreSearchResult,
    VectorStoresPage,
    WebhookEventResult,
    normalize_messages,
)
from .spec import RequestContext, RequestSpec

__all__ = [
    "Role",
    "Message",
    "MessageInput",
    "ToolCall",
    "ToolCallDelta",
    "UploadResource",
    "UploadPartResource",
    "Usage",
    "StreamEventType",
    "StreamEvent",
    "CompletionResult",
    "BackgroundResponseResult",
    "DeepResearchRunResult",
    "ConversationResource",
    "CompactionResult",
    "DeletionResult",
    "FileResource",
    "FilesPage",
    "FileContentResult",
    "ConversationItemResource",
    "ConversationItemsPage",
    "ModerationResult",
    "GeneratedImage",
    "ImageGenerationResult",
    "AudioTranscriptionResult",
    "AudioSpeechResult",
    "VectorStoreResource",
    "VectorStoresPage",
    "VectorStoreSearchResult",
    "FineTuningJobResult",
    "FineTuningJobsPage",
    "FineTuningJobEventsPage",
    "RealtimeClientSecretResult",
    "RealtimeCallResult",
    "RealtimeTranscriptionSessionResult",
    "RealtimeEventResult",
    "RealtimeConnection",
    "WebhookEventResult",
    "VectorStoreFileResource",
    "VectorStoreFilesPage",
    "VectorStoreFileContentResult",
    "VectorStoreFileBatchResource",
    "EmbeddingResult",
    "NormalizedOutputItem",
    "RequestContext",
    "RequestSpec",
    "CancellationToken",
    "CancelledError",
    "normalize_messages",
]
