DOMAINS = {
    "Natural Sciences": {
        "Physics": "The study of matter, energy, motion, and the fundamental forces of nature, from subatomic particles to cosmological phenomena.",
        "Chemistry": "The science of the composition, structure, properties, and reactions of substances, including their transformations and interactions.",
        "Biological Sciences": "The study of living organisms, their structure, function, evolution, and interactions with each other and their environments.",
        "Earth & Planetary Sciences": "The study of Earth's structure, processes, materials, and history, as well as the geology and composition of other planetary bodies.",
        "Astronomy & Astrophysics": "The scientific study of celestial objects, space, and the physical processes governing the universe beyond Earth's atmosphere.",
        "Environmental Science": "The interdisciplinary study of physical, chemical, and biological processes in the environment, and their impact on ecosystems and humans.",
    },

    "Formal Sciences": {
        "Mathematics (Pure & Applied)": "The study of abstract structures, patterns, and relationships, and their application to solving real-world quantitative problems.",
        "Statistics": "The science of collecting, analyzing, interpreting, and presenting data to understand patterns, variability, and uncertainty.",
        "Logic": "The systematic study of valid reasoning, argument structures, and principles of correct inference.",
        "Operations Research": "The use of mathematical modeling, optimization, and analytical methods to support decision-making in complex systems.",
        "Numerical Analysis": "The development and analysis of algorithms for approximating solutions to mathematical problems using computation.",
        "Systems Science": "The interdisciplinary study of complex systems in nature, society, and technology, focusing on their structure, dynamics, and behavior.",
    },

    "Engineering & Technology": {
        "Civil & Structural Engineering": "The design, construction, and maintenance of infrastructure such as buildings, bridges, roads, and water systems.",
        "Mechanical & Mechatronics Engineering": "The design, analysis, and manufacturing of mechanical systems, integrating mechanical, electrical, and computer engineering.",
        "Electrical & Electronic Engineering": "The study and application of electricity, electronics, and electromagnetism for power systems, devices, and communications.",
        "Chemical & Process Engineering": "The application of chemistry, physics, and engineering to design processes for transforming raw materials into useful products.",
        "Materials & Metallurgical Engineering": "The study of the properties, development, and processing of materials, including metals, ceramics, polymers, and composites.",
        "Aerospace Engineering": "The design, development, and testing of aircraft, spacecraft, and related systems and technologies.",
        "Industrial & Systems Engineering": "The optimization of complex processes, systems, and organizations to improve efficiency, quality, and productivity.",
        "Environmental Engineering": "The application of engineering principles to protect the environment, improve sustainability, and manage natural resources.",
        "Energy & Power Engineering": "The generation, conversion, transmission, and utilization of energy, including renewable and sustainable energy technologies.",
        "Robotics & Automation": "The design and implementation of robotic systems and automated processes for manufacturing, exploration, and service tasks.",
        "Telecommunications Engineering": "The design, implementation, and management of communication systems and networks for transmitting information.",
        "Computer Engineering (Hardware)": "The design and development of computer hardware, embedded systems, and integrated circuits.",
        "Manufacturing & Production Engineering": "The planning, design, and optimization of manufacturing processes, equipment, and systems.",
        "Mining & Resources Engineering": "The extraction and processing of minerals, metals, and other geological resources in a safe and sustainable manner.",
        "Nanotechnology": "The study, design, and application of materials and devices at the nanoscale for use in electronics, medicine, and energy."
    },

    "Computing & Information Technology": {
        "Computer Science (Algorithms & Theory)": "The study of computational theory, algorithms, complexity, and formal methods for solving problems efficiently.",
        "Software Engineering": "The application of engineering principles to the design, development, testing, and maintenance of software systems.",
        "Data Science & Analytics": "The extraction of insights from structured and unstructured data using statistical, computational, and machine learning techniques.",
        "Artificial Intelligence & Machine Learning": "The development of systems and algorithms that can learn, reason, and adapt to perform tasks requiring human-like intelligence.",
        "Cybersecurity": "The practice of protecting computer systems, networks, and data from unauthorized access, attack, or damage.",
        "Networks & Distributed Systems": "The design and management of interconnected systems and protocols that enable communication and resource sharing.",
        "Human-Computer Interaction": "The study and design of interfaces and systems that facilitate effective interaction between humans and computers.",
        "Information Systems / IT": "The planning, implementation, and management of technology systems to support organizational operations and decision-making.",
        "Cloud & Web Systems": "The development and deployment of scalable computing services, applications, and platforms via the internet.",
        "Game Technologies": "The design and implementation of interactive digital games, including graphics, physics, AI, and user experience.",
    },

    "Medical & Health Sciences": {
        "Clinical Medicine": "The diagnosis, treatment, and prevention of diseases and conditions in human patients through direct clinical care.",
        "Dentistry": "The prevention, diagnosis, and treatment of oral health conditions affecting teeth, gums, and the mouth.",
        "Pharmacy": "The preparation, dispensing, and appropriate use of medicines, along with pharmaceutical research and development.",
        "Nursing": "The care of individuals, families, and communities to maintain or recover optimal health and quality of life.",
        "Public Health & Epidemiology": "The protection and improvement of community health through disease prevention, policy, and population-level analysis.",
        "Biomedical Engineering": "The application of engineering principles to develop medical devices, diagnostics, and healthcare technologies.",
        "Medical Imaging & Radiology": "The use of imaging technologies such as X-rays, MRI, and ultrasound to diagnose and monitor medical conditions.",
        "Health Informatics": "The integration of healthcare and information technology to manage health data and improve patient care.",
        "Allied Health (Physio, OT, SLP, Audiology)": "Specialized healthcare fields providing physical rehabilitation, occupational therapy, speech-language pathology, and hearing care.",
        "Nutrition & Dietetics": "The science of food, nutrition, and diet planning to promote health and manage disease.",
        "Kinesiology & Exercise Science": "The study of human movement, physical activity, and exercise to enhance health and performance.",
        "Paramedicine & Emergency Care": "The provision of urgent medical care in emergency and pre-hospital settings.",
        "Midwifery": "The care and support of individuals during pregnancy, childbirth, and postpartum recovery.",
    },

    "Agricultural & Environmental Sciences": {
        "Agronomy & Crop Science": "The science of crop production, soil management, and agricultural resource optimization.",
        "Horticulture": "The cultivation and management of fruits, vegetables, flowers, and ornamental plants.",
        "Soil Science": "The study of soil properties, formation, and management for agriculture and environmental health.",
        "Animal Science & Husbandry": "The breeding, care, and management of livestock for food production and other uses.",
        "Fisheries & Aquaculture": "The management and cultivation of aquatic species for food, conservation, and economic purposes.",
        "Food Science & Technology": "The study and application of food processing, preservation, safety, and innovation.",
        "Forestry & Wildlife Management": "The sustainable management of forests and wildlife habitats for conservation and resource use.",
        "Sustainable Agriculture": "Agricultural practices that maintain productivity while conserving resources and minimizing environmental impact.",
        "Agricultural Economics": "The analysis of economic factors affecting agriculture, including production, markets, and policy.",
        "Conservation & Biodiversity": "The protection and management of species diversity, ecosystems, and natural resources.",
        "Pollution Control (Air/Water)": "The prevention and reduction of air and water pollution through technology and policy.",
        "Waste Management & Circular Economy": "The sustainable handling of waste materials, emphasizing recycling, reuse, and resource recovery.",
        "Sustainability Management": "The integration of environmental, social, and economic goals in organizational and policy decisions.",
        "Renewable Energy Systems (Applied)": "The design and implementation of technologies that harness renewable energy sources for practical use.",
        "Occupational Health & Safety": "The prevention of workplace hazards and promotion of safe, healthy working environments."
    },

    "Architecture & Built Environment": {
        "Architecture": "The design and planning of buildings and structures, integrating aesthetics, functionality, and structural integrity.",
        "Urban & Regional Planning": "The strategic design and regulation of land use, infrastructure, and services to create sustainable communities.",
        "Construction Management": "The coordination, planning, and control of construction projects from inception to completion.",
        "Geomatics & Cartography": "The collection, analysis, and presentation of geographic data for mapping and spatial decision-making.",
        "Real Estate Development (Technical)": "The technical aspects of planning, designing, and executing real estate projects, including site analysis and construction.",
        "Landscape Architecture": "The design of outdoor spaces that integrate environmental, social, and aesthetic considerations.",
    },

    "Business, Management & Finance": {
        "Accounting & Auditing": "The measurement, analysis, and verification of financial information for decision-making and compliance.",
        "Finance, Banking & Insurance": "The management of money, investments, financial institutions, and risk protection services.",
        "Marketing & Consumer Research": "The study of markets, consumer behavior, and strategies for promoting products and services.",
        "Operations & Supply Chain Management": "The design and optimization of processes for producing and delivering goods and services.",
        "Business Analytics": "The use of data analysis and statistical methods to inform business decision-making.",
        "Entrepreneurship & Innovation": "The creation and growth of new ventures through innovative products, services, and business models.",
        "International Business": "The management of business operations in global markets, addressing cultural, legal, and economic differences.",
        "Human Resource Management": "The strategic management of people in organizations, including recruitment, development, and performance.",
        "Corporate Governance": "The systems and practices that guide ethical, transparent, and effective organizational decision-making.",
        "Hospitality & Tourism Management": "The business and operational management of hotels, restaurants, and tourism services.",
        "Sports Management": "The administration, marketing, and event coordination of sports organizations and activities.",
        "Real Estate & Property Management": "The operation, control, and oversight of real estate assets for value preservation and growth.",
        "E-commerce & Digital Business": "The operation of online businesses and digital platforms for buying, selling, and delivering products or services.",
    },

    "Law & Public Policy": {
        "Jurisprudence & Legal Theory": "The philosophical and theoretical study of the nature, purposes, and principles of law.",
        "Criminal Law & Justice": "The body of law that defines crimes, their prosecution, and the justice system’s processes.",
        "Public & Administrative Law": "The regulation of relationships between individuals and the state, including government actions.",
        "Private & Civil Law": "The laws governing relationships between individuals or organizations, including contracts and property.",
        "International Law": "The legal frameworks governing relations between nations, organizations, and individuals across borders.",
        "Intellectual Property Law": "The protection and enforcement of rights related to inventions, creative works, and trademarks.",
        "Human Rights Law": "The legal protections of fundamental rights and freedoms for all individuals.",
        "Environmental & Natural Resources Law": "The legal frameworks for managing environmental protection and resource use.",
        "Tax Law": "The regulation of taxation, compliance, and tax-related dispute resolution.",
        "Immigration & Refugee Law": "The laws governing the movement, residency, and protection of people across borders.",
        "Labour & Employment Law": "The regulation of employment relationships, including worker rights and employer obligations.",
        "Dispute Resolution & Mediation": "The processes of resolving conflicts through negotiation, mediation, or arbitration.",
    },

    "Education": {
        "Teacher Education (Primary/Secondary)": "The preparation of teachers for primary and secondary school instruction and student development.",
        "Curriculum & Instruction": "The design, development, and delivery of educational content and teaching strategies.",
        "Educational Leadership & Administration": "The management and leadership of schools and educational institutions.",
        "Educational Policy & Research": "The study and development of policies to improve educational systems and outcomes.",
        "Assessment & Evaluation": "The measurement of learning outcomes, student progress, and program effectiveness.",
        "Instructional Design": "The creation of effective learning experiences and educational materials.",
        "Educational Technology": "The use of technology to enhance teaching, learning, and educational management.",
        "Higher Education Administration": "The governance and management of universities, colleges, and post-secondary institutions.",
        "Adult & Continuing Education": "The provision of learning opportunities for adult learners and professionals.",
        "Counseling in Education": "The support of students’ academic, career, and personal development through counseling services.",
        "Special & Inclusive Education": "The adaptation of education to meet the needs of students with disabilities or diverse learning profiles."
    },

    "Communication, Media & Information": {
        "Journalism": "The practice of researching, reporting, and producing news and stories across print, broadcast, and digital media platforms.",
        "Media & Cultural Studies": "The analysis of media content, industries, and cultural practices, exploring their influence on society and identity.",
        "Mass Communication": "The study of how information is transmitted to large audiences through various channels, including television, radio, and online platforms.",
        "Public Relations": "The strategic management of communication between organizations and their publics to maintain positive relationships and reputation.",
        "Advertising": "The creation and delivery of persuasive messages to promote products, services, or ideas to target audiences.",
        "Publishing & Editing": "The preparation, production, and distribution of written and visual content for books, magazines, and digital media.",
        "Library & Information Science": "The organization, management, and preservation of information resources in libraries and archives.",
        "Information Management": "The systematic collection, storage, and dissemination of information to support decision-making and knowledge sharing.",
        "Film & Screen Studies / Production": "The study and creation of film and screen media, including production, directing, editing, and critical analysis.",
    },

    "Social Sciences": {
        "Economics": "The study of how resources are produced, distributed, and consumed, including microeconomic and macroeconomic perspectives.",
        "Psychology": "The scientific study of mental processes, emotions, and behavior in individuals and groups.",
        "Sociology": "The study of social structures, relationships, and institutions, and how they influence human behavior.",
        "Political Science": "The analysis of political systems, governance, policies, and political behavior.",
        "Anthropology": "The study of human societies, cultures, and their historical and evolutionary development.",
        "Human Geography": "The examination of spatial relationships between people, places, and environments.",
        "Demography": "The statistical study of population dynamics, including birth, death, and migration patterns.",
        "International Relations": "The study of interactions between nations, including diplomacy, conflict, and global governance.",
        "Peace & Conflict Studies": "The study of conflict causes, prevention strategies, and methods for building sustainable peace.",
        "Gender & Intersectionality Studies": "The analysis of gender roles and identities in relation to social categories such as race, class, and sexuality.",
    },

    "Humanities": {
        "History": "The study and interpretation of past events, societies, and cultures.",
        "Philosophy & Ethics": "The exploration of fundamental questions about reality, knowledge, and morality.",
        "Linguistics": "The scientific study of language structure, usage, and evolution.",
        "Literature & Comparative Literature": "The analysis and comparison of written works across cultures and historical periods.",
        "Archaeology": "The study of past human life through material remains, artifacts, and excavation.",
        "Cultural & Area Studies": "The interdisciplinary study of specific regions or cultures, their histories, languages, and social dynamics.",
        "Religious Studies & Theology": "The academic study of religious beliefs, practices, and theological concepts.",
        "Classics": "The study of ancient Greek and Roman civilizations, languages, and literature.",
        "Translation & Interpretation": "The practice of rendering spoken or written material from one language into another.",
    },

    "Arts & Design": {
        "Visual Arts (Drawing, Painting, Sculpture)": "The creation of artworks through traditional visual mediums to express ideas, emotions, or aesthetics.",
        "Graphic & Communication Design": "The visual communication of ideas using typography, imagery, and layout design.",
        "Fashion & Textile Design": "The creation and design of clothing, accessories, and fabrics, blending aesthetics and function.",
        "Industrial & Product Design": "The design of functional and aesthetic products for mass production or specialized use.",
        "Photography": "The art and technique of capturing and editing images to convey meaning or tell a story.",
        "Performing Arts (Theatre, Dance, Music)": "Live artistic performances that combine creative expression with audience engagement.",
        "Music Performance & Composition": "The interpretation, creation, and arrangement of musical works across genres and styles.",
        "Digital Media Arts": "The creation of multimedia works using digital tools, including animation, video, and interactive media.",
        "Art History & Theory": "The study of artistic movements, styles, and cultural influences across time.",
        "Art Therapy": "The use of creative processes to promote mental, emotional, and physical well-being.",
        "Craft & Material Practices": "The design and creation of handcrafted works using materials such as wood, textiles, ceramics, or metal.",
    },

    "Security, Defense & Emergency Studies": {
        "Policing & Law Enforcement Studies": "The study of law enforcement systems, practices, and community safety strategies.",
        "Criminology (Applied)": "The practical application of criminological theories to understand and address crime and justice issues.",
        "Fire & Emergency Services": "The training and operations involved in fire prevention, firefighting, and emergency response.",
        "Emergency Management & Disaster Risk": "The planning and coordination of responses to natural and man-made disasters to minimize risk and impact.",
        "Military & Defense Studies": "The study of armed forces operations, defense strategies, and security policy.",
        "Private Security & Risk Management": "The protection of people, property, and information through security planning and risk assessment."
    }
}
