"""
Generic service adaptor contracts for llm-client.

This namespace defines stable, storage-agnostic adaptor interfaces and tool
helpers for external services commonly used by agents and tool runtimes.
"""

from .base import (
    AdaptorExecutionOptions,
    AdaptorCapability,
    AdaptorError,
    AdaptorMetadata,
    AdaptorOperation,
    AdaptorRuntime,
    AdaptorTimeoutError,
)
from .redis import (
    RedisAdaptor,
    RedisDeleteRequest,
    RedisDeleteResult,
    RedisGetRequest,
    RedisGetResult,
    RedisHashDeleteRequest,
    RedisHashDeleteResult,
    RedisHashGetRequest,
    RedisHashGetResult,
    RedisHashSetRequest,
    RedisHashSetResult,
    RedisKVAdaptor,
    RedisSafetyError,
    RedisSetRequest,
    RedisSetResult,
)
from .sql import (
    MySQLSQLAdaptor,
    PostgresSQLAdaptor,
    SQLAdaptor,
    SQLDialect,
    SQLExecutionResult,
    SQLMutationRequest,
    SQLQueryRequest,
    SQLQueryResult,
    SQLSafetyError,
    is_read_only_statement,
)
from .tools import (
    build_redis_delete_tool,
    build_redis_get_tool,
    build_redis_hash_delete_tool,
    build_redis_hash_get_tool,
    build_redis_hash_set_tool,
    build_redis_set_tool,
    build_sql_execute_tool,
    build_sql_query_tool,
    build_vector_delete_tool,
    build_vector_search_tool,
    build_vector_upsert_tool,
)
from .vector import (
    QdrantVectorAdaptor,
    VectorAdaptor,
    VectorDeleteRequest,
    VectorDeleteResult,
    VectorPoint,
    VectorSafetyError,
    VectorSearchMatch,
    VectorSearchRequest,
    VectorSearchResult,
    VectorUpsertRequest,
    VectorUpsertResult,
)

__all__ = [
    "AdaptorCapability",
    "AdaptorError",
    "AdaptorExecutionOptions",
    "AdaptorMetadata",
    "AdaptorOperation",
    "AdaptorRuntime",
    "AdaptorTimeoutError",
    "MySQLSQLAdaptor",
    "PostgresSQLAdaptor",
    "SQLAdaptor",
    "SQLDialect",
    "SQLExecutionResult",
    "SQLMutationRequest",
    "SQLQueryRequest",
    "SQLQueryResult",
    "SQLSafetyError",
    "is_read_only_statement",
    "RedisAdaptor",
    "RedisDeleteRequest",
    "RedisDeleteResult",
    "RedisGetRequest",
    "RedisGetResult",
    "RedisHashDeleteRequest",
    "RedisHashDeleteResult",
    "RedisHashGetRequest",
    "RedisHashGetResult",
    "RedisHashSetRequest",
    "RedisHashSetResult",
    "RedisKVAdaptor",
    "RedisSafetyError",
    "RedisSetRequest",
    "RedisSetResult",
    "QdrantVectorAdaptor",
    "VectorAdaptor",
    "VectorDeleteRequest",
    "VectorDeleteResult",
    "VectorPoint",
    "VectorSafetyError",
    "VectorSearchMatch",
    "VectorSearchRequest",
    "VectorSearchResult",
    "VectorUpsertRequest",
    "VectorUpsertResult",
    "build_redis_delete_tool",
    "build_redis_get_tool",
    "build_redis_hash_delete_tool",
    "build_redis_hash_get_tool",
    "build_redis_hash_set_tool",
    "build_redis_set_tool",
    "build_sql_execute_tool",
    "build_sql_query_tool",
    "build_vector_delete_tool",
    "build_vector_search_tool",
    "build_vector_upsert_tool",
]
